// 12_weeks_ftp_builder/program.config.ts
import type { ProgramConfig } from '../../lib/types.js';

export const config: ProgramConfig = {
  name: '12 Weeks Ftp Builder',
  description: 'TODO: Add program description',

  schedule: [
    {
      week: 1,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W01-D2-Tuesday-FTP_Test.zwo',
    },
    {
      week: 1,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W01-D3-Wednesday-Recovery.zwo',
    },
    {
      week: 1,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W01-D4-Thursday-Tempo.zwo',
    },
    {
      week: 1,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W01-D6-Saturday-Endurance.zwo',
    },
    {
      week: 1,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W01-D7-Sunday-Recovery.zwo',
    },
    {
      week: 2,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W02-D2-Tuesday-Sweet_Spot.zwo',
    },
    {
      week: 2,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W02-D3-Wednesday-Easy_Spin.zwo',
    },
    {
      week: 2,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W02-D4-Thursday-FTP_Intervals.zwo',
    },
    {
      week: 2,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W02-D6-Saturday-Tempo_Endurance.zwo',
    },
    {
      week: 2,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W02-D7-Sunday-Long_Endurance.zwo',
    },
    {
      week: 3,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W03-D2-Tuesday-Over_Unders.zwo',
    },
    {
      week: 3,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W03-D3-Wednesday-Recovery.zwo',
    },
    {
      week: 3,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W03-D4-Thursday-Extended_Threshold.zwo',
    },
    {
      week: 3,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W03-D6-Saturday-Sweet_Spot_Progression.zwo',
    },
    {
      week: 3,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W03-D7-Sunday-Easy_Spin.zwo',
    },
    {
      week: 4,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W04-D2-Tuesday-Recovery_Cadence.zwo',
    },
    {
      week: 4,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W04-D4-Thursday-Light_Tempo.zwo',
    },
    {
      week: 4,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W04-D6-Saturday-Easy_Endurance.zwo',
    },
    {
      week: 4,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W04-D7-Sunday-Recovery.zwo',
    },
    {
      week: 5,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W05-D2-Tuesday-Pyramid_Intervals.zwo',
    },
    {
      week: 5,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W05-D3-Wednesday-Easy_Spin.zwo',
    },
    {
      week: 5,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W05-D4-Thursday-Progressive_Threshold.zwo',
    },
    {
      week: 5,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W05-D6-Saturday-Tempo_Endurance_Long.zwo',
    },
    {
      week: 5,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W05-D7-Sunday-Long_Endurance.zwo',
    },
    {
      week: 6,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W06-D2-Tuesday-Push_and_Pull.zwo',
    },
    {
      week: 6,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W06-D3-Wednesday-Recovery.zwo',
    },
    {
      week: 6,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W06-D4-Thursday-FTP_2x20.zwo',
    },
    {
      week: 6,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W06-D6-Saturday-Sweet_Spot_3x22.zwo',
    },
    {
      week: 6,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W06-D7-Sunday-Endurance.zwo',
    },
    {
      week: 7,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W07-D2-Tuesday-VO2max_30_30s.zwo',
    },
    {
      week: 7,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W07-D3-Wednesday-Easy_Spin.zwo',
    },
    {
      week: 7,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W07-D4-Thursday-FTP_30min.zwo',
    },
    {
      week: 7,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W07-D6-Saturday-Sweet_Spot_3x25.zwo',
    },
    {
      week: 7,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W07-D7-Sunday-Endurance_Tempo.zwo',
    },
    {
      week: 8,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W08-D2-Tuesday-Recovery_Cadence.zwo',
    },
    {
      week: 8,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W08-D4-Thursday-Light_Tempo.zwo',
    },
    {
      week: 8,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W08-D6-Saturday-Easy_Endurance.zwo',
    },
    {
      week: 8,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W08-D7-Sunday-Recovery.zwo',
    },
    {
      week: 9,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W09-D2-Tuesday-Pyramid_Intervals.zwo',
    },
    {
      week: 9,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W09-D3-Wednesday-Easy_Spin.zwo',
    },
    {
      week: 9,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W09-D4-Thursday-FTP_3x15.zwo',
    },
    {
      week: 9,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W09-D6-Saturday-Tempo_Endurance.zwo',
    },
    {
      week: 9,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W09-D7-Sunday-Long_Endurance.zwo',
    },
    {
      week: 10,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W10-D2-Tuesday-VO2max_40_20s.zwo',
    },
    {
      week: 10,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W10-D3-Wednesday-Recovery.zwo',
    },
    {
      week: 10,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W10-D4-Thursday-FTP_2x25.zwo',
    },
    {
      week: 10,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W10-D6-Saturday-Sweet_Spot_3x25.zwo',
    },
    {
      week: 10,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W10-D7-Sunday-Endurance.zwo',
    },
    {
      week: 11,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W11-D2-Tuesday-VO2max_Mixed.zwo',
    },
    {
      week: 11,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W11-D3-Wednesday-Easy_Spin.zwo',
    },
    {
      week: 11,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W11-D4-Thursday-FTP_35min.zwo',
    },
    {
      week: 11,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W11-D6-Saturday-Race_Simulation.zwo',
    },
    {
      week: 11,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W11-D7-Sunday-Endurance.zwo',
    },
    {
      week: 12,
      day: 2,
      dayName: 'Tuesday',
      zwoFile: 'W12-D2-Tuesday-Final_FTP_Test.zwo',
    },
    {
      week: 12,
      day: 3,
      dayName: 'Wednesday',
      zwoFile: 'W12-D3-Wednesday-Easy_Spin.zwo',
    },
    {
      week: 12,
      day: 4,
      dayName: 'Thursday',
      zwoFile: 'W12-D4-Thursday-Victory_Lap.zwo',
    },
    {
      week: 12,
      day: 6,
      dayName: 'Saturday',
      zwoFile: 'W12-D6-Saturday-Celebration_Ride.zwo',
    },
    {
      week: 12,
      day: 7,
      dayName: 'Sunday',
      zwoFile: 'W12-D7-Sunday-Recovery.zwo',
    },
  ],

  tags: ['TODO'],
  targetAudience: 'TODO: Define target audience',
};
